### PR TITLE
Added Symmetric Key Functionality

### PR DESCRIPTION
**Pull request by n0900**
Extended COSE/JOSE Data structure to now handle symmetric key as input

### CODE REVIEW

**Comment by JesusMcCloud** [comment]
You mentioned JWKs also support symmetric keys? why not add them as well?

**Comment by n0900** [comment]
> You mentioned JWKs also support symmetric keys? why not add them as well?

adding a 'k'-value should be enough to provide this, no?

**Comment by JesusMcCloud** [comment]
> > You mentioned JWKs also support symmetric keys? why not add them as well?
> 
> adding a 'k'-value should be enough to provide this, no?

You tell me… I'm not the one who read the RFC ;-)

**Review by JesusMcCloud — CHANGES_REQUESTED** [review]
Please do the same for JsonWebKey

**Review by JesusMcCloud — APPROVED** [review]

**Pull request merged**
