### PR TITLE
Tmp/json key id on init

### PR DESCRIPTION
**Pull request by n0900**
When a JsonWebKey is created from a CryptopublicKey which in turn was created by a keyPair it does not have a keyId. However if we transform this JsonWebKey back to a CryptoPublicKey the identifier gets saved to keyId and if we then transform it back again to JsonWebKey it now has a keyid -> the previous identifier.

As an easy fix I propose this change, however other ideas are welcome.

### CODE REVIEW

**Comment by nodh** [comment]
But won't this also add a keyId, when converting from a JWK to a CryptoPublicKey and then back again?

**Comment by iaik-jheher** [comment]
So if I understand you correctly, the conversion from `JsonWebKey` (no keyId) to `CryptoPublicKey` is adding a key ID, where none exists?

If so, why isn't that the issue to fix?

**Comment by n0900** [comment]
> But won't this also add a keyId, when converting from a JWK to a CryptoPublicKey and then back again?

True, this will override a JWK kid if it was null to begin with. Not perfect.

**Comment by n0900** [comment]
> So if I understand you correctly, the conversion from `JsonWebKey` (no keyId) to `CryptoPublicKey` is adding a key ID, where none exists?
> 
> If so, why isn't that the issue to fix?

Because if we fix it like that then no JsonWebKey we generate using our library will ever have a keyID, which might not be ideal

**Comment by iaik-jheher** [comment]
Maybe it should be possible to specify a keyId when converting to `JsonWebKey`, then?

**Comment by n0900** [comment]
> Maybe it should be possible to specify a keyId when converting to `JsonWebKey`, then?

we could lift the additional property from the jsonwebkey to a main property of the CryptoPublicKey itself, what do you think of the recent commit as a base? If this is okay I will extend it for JWK and COSE.

**Comment by n0900** [comment]
Obviously we would then need remove the additional property

**Review by iaik-jheher — APPROVED** [review]
@JesusMcCloud @n0900 review please, this should address the issue

**Review by nodh — APPROVED** [review]
great!

**Review by nodh — APPROVED** [review]

**Comment by nodh** [comment]
Better to squash all commits into one when merging? (-:

**Pull request merged**
