### PR TITLE
Remove identifier from JsonWebKey

### PR DESCRIPTION
**Pull request by nodh**

### CODE REVIEW

**Review by n0900 — APPROVED** [review]

**Comment by iaik-jheher** [comment]
I wonder if we could maybe have a `SpecializedCryptoPublicKey` interface for JWK, COSE, etc., keys, to parallel the `SpecializedCryptoAlgorithm` interface...

**Review by JesusMcCloud — APPROVED** [review]

**Comment by JesusMcCloud** [comment]
> I wonder if we could maybe have a `SpecializedCryptoPublicKey` interface for JWK, COSE, etc., keys, to parallel the `SpecializedCryptoAlgorithm` interface...

These are mostly used as containers for specific use cases and the serialization is the key part. Also: serialization is where JWK is nice and smooth and CoseKey serialization is the what a the perceptive issues of a schizophrenic would look like it if you could translate it to kotlin code. Hence, this might me overkill

**Comment by iaik-jheher** [comment]
Not part of this PR anyway, I'll play around with it.

**Review by iaik-jheher — APPROVED** [review]

**Comment by JesusMcCloud** [comment]
> Not part of this PR anyway, I'll play around with it separately.

After all the signers are implemented, i presume ;-)

**Pull request merged**
